# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b742c748-5cd4-4d63-81d5-630b512fe986'
  imageRepository: 'exopekexopekbackend'
  containerRegistry: 'exopekbackend.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - script: docker build -t $(imageRepository):$(tag) -f $(dockerfilePath) .
        displayName: Build Step
- stage: Push
  displayName: Push stage
  jobs:
    - job: Push
      displayName: Push
      pool:
        vmImage: $(vmImageName)
      steps:
        - script: echo "Pushing..."
          displayName: Push Step
