// <auto-generated />
using System;
using EXOPEK_Backend.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EXOPEK_Backend.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230809234743_2023-08-10-js-1")]
    partial class _20230810js1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EXOPEK_Backend.Entities.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("EXOPEK_Backend.Entities.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("EXOPEK_Backend.Entities.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("EXOPEK_Backend.Entities.Models.WorkoutVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutVideo");
                });

            modelBuilder.Entity("EXOPEK_Backend.Entities.Models.Image", b =>
                {
                    b.HasOne("EXOPEK_Backend.Entities.Models.Workout", null)
                        .WithMany("Images")
                        .HasForeignKey("WorkoutId");
                });

            modelBuilder.Entity("EXOPEK_Backend.Entities.Models.WorkoutVideo", b =>
                {
                    b.HasOne("EXOPEK_Backend.Entities.Models.Video", "Video")
                        .WithMany("WorkoutVideos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EXOPEK_Backend.Entities.Models.Workout", "Workout")
                        .WithMany("WorkoutVideos")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("EXOPEK_Backend.Entities.Models.Video", b =>
                {
                    b.Navigation("WorkoutVideos");
                });

            modelBuilder.Entity("EXOPEK_Backend.Entities.Models.Workout", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("WorkoutVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
